apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1
  kind: Gateway
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.networking.k8s.io/v1","kind":"Gateway","metadata":{"annotations":{},"name":"lab-gateway","namespace":"harbor"},"spec":{"gatewayClassName":"cilium","listeners":[{"allowedRoutes":{"namespaces":{"from":"Same"}},"name":"http","port":80,"protocol":"HTTP"},{"allowedRoutes":{"namespaces":{"from":"Same"}},"name":"https","port":443,"protocol":"HTTPS","tls":{"certificateRefs":[{"name":"harbor-tls"}],"mode":"Terminate"}}]}}
    creationTimestamp: "2026-04-11T12:50:47Z"
    generation: 3
    name: lab-gateway
    namespace: harbor
    resourceVersion: "5141407"
    uid: d9974003-577f-4509-af20-f05dbaa2beda
  spec:
    gatewayClassName: cilium
    listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
        - group: ""
          kind: Secret
          name: harbor-tls
        mode: Terminate
  status:
    addresses:
    - type: IPAddress
      value: 10.113.24.96
    conditions:
    - lastTransitionTime: "2026-04-18T08:32:13Z"
      message: Gateway successfully scheduled
      observedGeneration: 3
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2026-05-10T09:00:06Z"
      message: Gateway Programmed
      observedGeneration: 3
      reason: Programmed
      status: "True"
      type: Programmed
    listeners:
    - attachedRoutes: 3
      conditions:
      - lastTransitionTime: "2026-05-10T09:00:06Z"
        message: Resolved Refs
        observedGeneration: 3
        reason: ResolvedRefs
        status: "True"
        type: ResolvedRefs
      - lastTransitionTime: "2026-05-10T09:00:06Z"
        message: Listener Accepted
        observedGeneration: 3
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2026-05-10T09:00:06Z"
        message: Listener Programmed
        observedGeneration: 3
        reason: Programmed
        status: "True"
        type: Programmed
      name: http
      supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
      - group: gateway.networking.k8s.io
        kind: GRPCRoute
    - attachedRoutes: 3
      conditions:
      - lastTransitionTime: "2026-05-10T09:00:06Z"
        message: Resolved Refs
        observedGeneration: 3
        reason: ResolvedRefs
        status: "True"
        type: ResolvedRefs
      - lastTransitionTime: "2026-05-10T09:00:06Z"
        message: Listener Accepted
        observedGeneration: 3
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2026-05-10T09:00:06Z"
        message: Listener Programmed
        observedGeneration: 3
        reason: Programmed
        status: "True"
        type: Programmed
      name: https
      supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
      - group: gateway.networking.k8s.io
        kind: GRPCRoute
kind: List
metadata:
  resourceVersion: ""
